In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import scipy as la

In [2]:
pip install seaborn

Note: you may need to restart the kernel to use updated packages.


In [9]:
import numpy as np

In [19]:
# Inversion of matrix(Transponse)
matrix1=np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
result=matrix1.T
print(result)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]


In [10]:
# The determinant of matrix
matrix1=np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
result=np.linalg.det(matrix1)
print(result)
print(f"The determinant of matrix1 is {result}")

0.2299999999999999
The determinant of matrix1 is 0.2299999999999999


In [11]:
from scipy.linalg import lu

In [14]:
# c.
# Matrix decomposition

matrix1=np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
L,U = lu(matrix1, True)
print(f'L is {L} ')
print(f' U is {U}')


L is [[1.         0.         0.        ]
 [0.2        1.         0.        ]
 [0.5        0.72916667 1.        ]] 
 U is [[1.         0.2        0.5       ]
 [0.         0.96       0.7       ]
 [0.         0.         0.23958333]]


In [16]:
from scipy.linalg import qr

In [18]:
matrix1=np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
Q,R= qr(matrix1, True)
print(f'Q is {Q} ')

print(f' R is {R}')

Q is [[-0.88045091  0.38615039 -0.27512557]
 [-0.17609018 -0.80507368 -0.566435  ]
 [-0.44022545 -0.4502713   0.77682515]] 
 R is [[-1.13578167 -0.70436073 -1.02132305]
 [ 0.         -1.08806065 -0.90125505]
 [ 0.          0.          0.18611436]]


In [17]:
# Transforming a matrix
matrix1=np.array([[1,0.2,0.5],[0.2,1,0.8],[0.5,0.8,1]])
result=matrix1.transpose()
print(result)

[[1.  0.2 0.5]
 [0.2 1.  0.8]
 [0.5 0.8 1. ]]
